[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "8w3yYANNkxV7bPCdQ25QEuPTZyaiFMS7ep9bfmxTzfQH"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
